name: titles
'on':
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  issues:
    types: [ opened ]
jobs:
  titles:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    permissions:
      issues: write
    steps:
      - uses: horw/issue-title-ai@b0597b667ccad0abc25aedd61ef702d1de46c5d0
        with:
          github-token: ${{ github.token }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          days-to-scan: 7
          skip-label: 'good-title'
          auto-update: true
          max-issues: 10
          verbose: true
          model: gpt-4
          strip-characters: "LA\"'"
          prompt: |-
            You are an expert at writing clear, concise, and descriptive GitHub issue titles.
            Please analyze the following issue title and determine if it needs improvement.
            If the title is already clear, specific, and well-formatted, return the original title unchanged.
            Otherwise, improve it to make it more specific, actionable, and easy to understand.
            The improved title should clearly communicate the problem or feature request.

            Original Issue Title: "{original_title}"

            Issue Description:
            \"\"\"
            {issue_body}
            \"\"\"

            Rules for a good issue title:
            1. It must sound like a bug report, assuring that something is broken
            2. Use aggressive tone, to ephasize the problem at hands
            3. Keep it concise (under 80 characters ideally)
            4. Avoid vague terms like "bug" or "issue" without context
            5. Don't change the meaning or intent of the original issue
            6. If the original title is already good enough, do not change it
            7. MUST END WITH LALALA AND WITH "'

            Your response should ONLY contain the improved issue title
            or the original title if it's already good.
            Do not include any other text or explanations.