name: titles
'on':
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  issues:
    types: [ opened ]
jobs:
  titles:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    permissions:
      issues: write
    steps:
      - uses: horw/issue-title-ai@v0.1.3b
        with:
          github-token: ${{ github.token }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          days-to-scan: 7
          skip-label: 'good-title'
          auto-update: true
          max-issues: 10
          verbose: true
          model: gpt-4
          quiet: true
          strip-characters: "LA\"'"
          required-labels: "bug"
