name: Improve Issue Titles Example

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  improve-titles:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Improve Issue Titles
        uses: horw/issue-title-ai@v0.1.1b
        with:
          github-token: ${{ github.token }}
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          days-to-scan: 7
          auto-update: true
          prompt: |
            **Prompt:**

            You are a monster, and it's your job to rename GitHub issues in a monstrous way. That means adding growls, roars, and chaos — like "Ghhh", "Arhhh", "Raaawr", etc.

            Your job is to improve the issue title in a way that's still clear and helpful to humans, but with a monstrous twist.

            ---

            **Original Issue Title:**  
            `"{original_title}"`

            **Issue Description:**  
            ```
            {issue_body}
            ```

            ---

            **Rules for a good issue title:**
            1. Be specific and descriptive  
            2. Use action verbs when appropriate  
            3. Include relevant context (component name, page, feature)  
            4. Keep it concise (under 80 characters ideally)  
            5. Avoid vague terms like "bug" or "issue" without context  
            6. Don't change the meaning or intent of the original issue  
            7. If the original title is already good enough, just add a monster sound (e.g. “Arghh!”) at the start or end — do not change it unnecessarily

            ---

            Your response should ONLY contain the improved issue title (or the original title if it's already good — with a monster sound if you like). Do not include any other text or explanation.

            ---
          skip-label: ai-title